
[[conventions-used-in-these-guidelines]]
== Conventions Used in These Guidelines

The requirement level keywords "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" used in this document (case insensitive) are to be
interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC
2119].

[[DNT-specific-information]]
== Zalando specific information

The purpose of our “RESTful API guidelines” is to define standards to
successfully establish “consistent API look and feel” quality.

These guidelines will, to some extent, remain work in progress as our
work evolves.

In case guidelines are changing, following rules apply:

* existing APIs don't have to be changed, but we recommend it
* clients of existing APIs have to cope with these APIs based on
outdated rules
* new APIs have to respect the current guidelines

Furthermore you should keep in mind that once an API becomes public
externally available, it has to be re-reviewed and changed according to
current guidelines - for sake of overall consistency.
